language: node_js
node_js: '6'
env:
  - VERSION=0.21.0
  - VERSION=0.22.0
  - VERSION=0.23.0
  - VERSION=0.24.0
  - VERSION=0.25.0
script:
  - npm i
  - mkdir -p ./node_modules/.bin
  - curl -SL "https://github.com/fibjs/fibjs/releases/download/v${VERSION}/fibjs-linux-x64" -o ./node_modules/.bin/fibjs
  - chmod a+x ./node_modules/.bin/fibjs
  - npm run ci
